### ISSUE TITLE
.DS_Store info disclosure

### ISSUE THREAD

**Issue by zachgrace-nm** [northwesternmutual/ai-challenge#1]
The https://github.com/northwesternmutual/ai-challenge/blob/master/tournamentService/.DS_Store file discloses your internal organization user name in embedded path `https://github.com/northwesternmutual/ai-challenge/blob/master/tournamentService/.DS_Store`

Here's some additional .DS_Store files you may want to delete:
* ./algorithmService/controllers/.DS_Store
* ./algorithmService/routes/.DS_Store
* ./tournamentService/src/.DS_Store
* ./tournamentService/.DS_Store
* ./tournamentService/controllers/.DS_Store

**Comment by hartalex** [comment]
We probably shouldn't be disclosing usernames in issues either. :)

**Comment by frankgreco** [comment]
good point! updated the issue description
