### ISSUE TITLE
Rotate Travis CI private token before public release

### ISSUE THREAD

**Issue by zachgrace-nm** [northwesternmutual/ai-challenge#2]
The Travis token used to in the build status image of the README.md file should not be made public according to: https://docs.travis-ci.com/user/status-images/

> This token is only used to access the build status image, but we recommend you not use it on a publicly available site.

Please rotate this token prior to releasing the code publicly.

**Comment by frankgreco** [comment]
fixed with commit b6039301b1599fce456425c508709c80c2154b19
