### ISSUE TITLE
Github token

### ISSUE THREAD

**Issue by zachgrace-nm** [northwesternmutual/ai-challenge#5]
There seems to be a number of different tokens that are being used to provide repo access to petstore.swagger.io.

An example in README.md is:

`http://petstore.swagger.io/?url=https://raw.githubusercontent.com/northwesternmutual/ai-challenge/master/swagger.yml?token=AVjpyXumkRz9yyVsZuQScvBV2i32e00Uks5YSEKzwA%3D%3D`

Like the Travis CI token, please destroy/rotate these tokens.

**Comment by frankgreco** [comment]
fixed with commit facd9b2c4f6b2d39aaf9dc5cc3ccffd933516447
